### ISSUE TITLE
SEP firmware is NOT being signed! on windows

### ISSUE THREAD

**Issue by GladYard** [CoocooFroggy/FutureRestore-GUI#66]

**Comment by morduk1** [comment]
Same here, i tryed alot of time , and same msg

**Comment by jaolvey** [comment]
getting same error - could be user error, but thought I'd check

**Comment by CoocooFroggy** [comment]
If you're using Latest SEP & BB, you need to check Download FutureRestore Beta in settings for iOS 15 SEP and BB support. Note that iOS 15 SEP is not compatible with iOS 14 versions on Face ID devices.

**Comment by jaolvey** [comment]
Perfect – thanks that worked

From: CoocooFroggy ***@***.***>
Date: Wednesday, November 10, 2021 at 3:54 PM
To: CoocooFroggy/FutureRestore-GUI ***@***.***>
Cc: Jay Olvey ***@***.***>, Comment ***@***.***>
Subject: Re: [CoocooFroggy/FutureRestore-GUI] SEP firmware is NOT being signed! on windows (Issue #66)

If you're using Latest SEP & BB, you need to check Download FutureRestore Beta in settings for iOS 15 SEP and BB support. Note that iOS 15 SEP is not compatible with iOS 14 versions on Face ID devices.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCoocooFroggy%2FFutureRestore-GUI%2Fissues%2F66%23issuecomment-965854207&data=04%7C01%7Cjay.olvey%40microsoft.com%7C9f80c677dadf460f986e08d9a4a56410%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637721852540977972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wh1Tv%2FPPxfO2dngSiUiXdAI1vk9HoEMFCK4rmY%2B2hfU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMU3HGCNFEPVK3TL3K3OBP3ULMA2DANCNFSM5GZRA3QQ&data=04%7C01%7Cjay.olvey%40microsoft.com%7C9f80c677dadf460f986e08d9a4a56410%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637721852540987968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z1KqXQQkz9pnuUc7U4c17iaThYxZvCBF3DCfJbt%2BjF8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjay.olvey%40microsoft.com%7C9f80c677dadf460f986e08d9a4a56410%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637721852540987968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZfOHskXrL%2Flx5qGwAfMYqNXivkP6656Ao6aY19IHsIs%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjay.olvey%40microsoft.com%7C9f80c677dadf460f986e08d9a4a56410%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637721852540997965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VQjpbhZ5AD7SlIJeoXeQDjpPcl4HTwMfRa%2BbDPnSO7I%3D&reserved=0>.

**Comment by Eason-Wong-801** [comment]
Can only macos futurerestore downgrade from ios15.1 ?
