### ISSUE TITLE
A11支持保留数据降级吗?

### ISSUE THREAD

**Issue by Misakei** [CoocooFroggy/FutureRestore-GUI#80]

**Comment by CoocooFroggy** [comment]
It depends on the current version and future version.

For example, going from > iOS 14.5 to < 14.5 did not work.

I do not think it has been tested yet, but I think the iOS 15 versions should be fine. Because you are A11, I think you can always set the generator and try again if it fails. Be sure to make a backup.

**Comment by Misakei** [comment]
@CoocooFroggy ok.thankyou.
